# Generated by Django 2.0.7 on 2018-07-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_auto_20180708_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='sizes',
            field=models.CharField(choices=[('thirty', '30cm'), ('fifty', '50cm')], default='thirty', max_length=6, unique=True),
        ),
    ]
