# Generated by Django 2.0.7 on 2018-07-08 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20180708_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='sizes',
            new_name='size',
        ),
    ]
