# Generated by Django 2.0.7 on 2018-07-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_auto_20180708_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='SKU_id',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
