# Generated by Django 2.0.7 on 2018-07-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_pizza_sku_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('thirty', '30cm'), ('fifty', '50cm')], max_length=6, unique=True),
        ),
    ]
