# Generated by Django 2.0.7 on 2018-07-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180710_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
